export * from "./setup.routes.js"
export * from "./auth.routes.js"
export * from "./teachers.routes.js"
export * from "./students.routes.js"
export * from "./course.routes.js"
export * from "./assignment.routes.js"